services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: wmsiq
      POSTGRES_USER: wmsiq
      POSTGRES_PASSWORD: wmsiq
      PGPASSWORD: wmsiq
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wmsiq"]
      interval: 5s
      timeout: 5s
      retries: 10
