CREATE OR REPLACE TRIGGER 
"OP"."OP1F_TRBIU" BEFORE UPDATE OR INSERT OF "LLR_TS" ON "OP"."LOAD_DEPART_OP1F" 
REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW 
begin
   :new.llr_dt := TRUNC(:new.llr_ts);
end;
/

